### ISSUE TITLE
Do the Linear Algebra package!

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/mason-registry#3] opened 2017-08-19 07:22 UTC
Go ahead, ask Ben A!  I'll watch, it'll be awesome.

**Comment by ben-albrecht** [comment] 2017-08-19 13:57
`mason` will not support non-Chapel code dependencies in version `0.1.0`. We're still determining if we want to kick off packages with C-dependencies as packages or not, because their usage will still require users to install other software on their own and specify additional compilation flags.

**Comment by ben-albrecht** [comment] 2019-04-05 15:20
I'm going to close this as a duplicate of the broader issue: https://github.com/chapel-lang/chapel/issues/10713

**Closed as completed by ben-albrecht** 2019-04-05 15:20 UTC
